server:
  port: 8080

management:
  endpoint:
    shutdown:
      enabled: true
  server:
    port: 8888
  endpoints:
    web:
      exposure:
        include: beans,shutdown
spring:
  redis:
    host: localhsot
    port: 6379
  elasticsearch:
    jest:
      uris: ["localhost:9092"]
  main:
    banner-mode: "off"
